name: build-linux-aarch64

on: [ push, pull_request ]

env:
  BUILD_PHP_VERSION: 8.2.28

jobs:
  linux-aarch64:
    if: 1
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Show Environment Info
        run: |
          echo $PATH
          env
          docker info
          id -u
          id -g
          who
          cat /etc/os-release
          hostnamectl
          uname -s
          uname -m
          uname -r

          cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c
          cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l
          cat /proc/cpuinfo | grep "cpu cores" | uniq
          cat /proc/cpuinfo| grep "processor"| wc -l
          lscpu

          export IPV6=$(ip -6 address show  | grep inet6 | awk '{print $2}' | cut -d'/' -f1 | sed -n '2p')
          export IPV4=$(ip -4 address show  | grep inet | grep -v 127.0.0 | awk '{print $2}' | cut -d'/' -f1 | sed -n '1p')
          echo $IPV4
          echo $IPV6
          echo "X_IPV6=${IPV6}" >> $GITHUB_ENV
          echo "X_IPV4=${IPV4}" >> $GITHUB_ENV

      - name: Prepare Build Environment
        run: |
          # git submodule update --init
          echo "BUILD_PHP_VERSION=${{ matrix.php-version }}" >> $GITHUB_ENV

          sudo mkdir -p /usr/local/swoole-cli
          uid=$(id -u) && gid=$(id -g) && sudo chown -R ${uid}:${gid} /usr/local/swoole-cli

          mkdir -p ${{ github.workspace }}/var/build-github-action-container/

      - name: Cache PHP Runtime
        uses: actions/cache@v4
        id: php-runtime-cache-aarch64
        with:
          path: ${{ github.workspace }}/runtime
          key: ${{ runner.os }}-aarch64-php-runtime

      - name: Cache PHP Vendor
        uses: actions/cache@v4
        id: php-vendor-cache-aarch64
        with:
          path: ${{ github.workspace }}/vendor
          key: ${{ runner.os }}-aarch64-php-vendor

      - name: Cache Dependency Source Code Tarball
        uses: actions/cache@v4
        id: pool-cache
        with:
          path: ${{ github.workspace }}/pool/
          key: source-code-tarball-pool

      - name: Cache all-library
        uses: actions/cache@v4
        id: all-library-cache-aarch64
        with:
          path: /usr/local/swoole-cli
          key: ${{ github.head_ref || github.ref_name }}-${{ runner.os }}-aarch64-all-library

      - name: Cache swoole-cli-builder-image
        uses: actions/cache@v4
        id: swoole-cli-builder-image-cache-aarch64
        with:
          path: ${{ github.workspace }}/var/build-github-action-container/swoole-cli-builder-image.tar
          key: ${{ runner.os }}-aarch64-swoole-cli-builder-image

      - name: Prepare swoole-cli-builder-image
        run: |
          if [ -f ${{ github.workspace }}/var/build-github-action-container/swoole-cli-builder-image.tar ] ; then
              docker load -i  ${{ github.workspace }}/var/build-github-action-container/swoole-cli-builder-image.tar
          else
              bash .github/workflows/build-alpine-builder-container.sh --platform "linux/arm64"
          fi

      - name: Prepare Runtime and Libraries and Extensions
        run: |
          set -x
          mkdir -p pool/lib
          mkdir -p pool/ext
          mkdir -p bin/
          mkdir -p runtime/
          if [ ! -f runtime/php ] ; then
              bash  setup-php-runtime.sh
          fi
          bash sapi/download-box/download-box-get-archive-from-server.sh
          ls -A pool/lib/
          ls -A /usr/local/swoole-cli/

      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: swoole-cli-builder:latest
          options: -v ${{ github.workspace }}:/work -w /work -e BUILD_PHP_VERSION=${{ env.BUILD_PHP_VERSION }} -v /usr/local/swoole-cli:/usr/local/swoole-cli
          run: |
            set -eux
            uname -m
            export PATH=/work/runtime:$PATH  # 容器已经内置 php 和 composer
            alias php="php -d curl.cainfo=/work/runtime/cacert.pem -d openssl.cafile=/work/runtime/cacert.pem"

            # sed -i 's/mirrors.tuna.tsinghua.edu.cn/dl-cdn.alpinelinux.org/g' /etc/apk/repositories
            # sed -i 's/mirrors.ustc.edu.cn/dl-cdn.alpinelinux.org/g' /etc/apk/repositories
            # bash sapi/quickstart/mark-install-library-cached.sh

            sh  sapi/quickstart/linux/alpine-init.sh
            composer install  --no-interaction --no-autoloader --no-scripts --profile --no-dev
            composer dump-autoload --optimize --profile --no-dev

            php prepare.php  +nginx --with-c-compiler=gcc --with-build-type=release

            bash make-install-deps.sh

            bash make.sh all-library

            bash make.sh config
            bash make.sh build
            bash make.sh archive

      - name: Show Build Result
        run: |
          ls ./bin/nginx
          ./bin/nginx/sbin/nginx -V
          file ./bin/nginx/sbin/nginx
          readelf -h ./bin/nginx/sbin/nginx

      - name: get app version
        run: |
          APP_VERSION=$(cat ./APP_VERSION)
          APP_NAME=$(cat ./APP_NAME)
          echo $APP_VERSION
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV
          echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV

      - name: production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-${{ env.NGINX_VERSION }}-linux-arm64
          retention-days: 90
          path: ./bin/nginx

      - name: gh release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.APP_NAME }}-${{ env.APP_VERSION }}-linux-arm64.tar.xz

